Repository GSG-G13/Petopia, pull requests merged in 2023-06, with the labels that each got.

#10 Project setup
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  __test__/index.test.ts
  client/index.ts
  example.env
  package-lock.json
  package.json
  src/index.ts
  tsconfig.json
Labels: Approved, Done

#12 Build server file structure
  .gitignore
  package-lock.json
  package.json
  src/app.ts
  src/controllers/index.ts
  src/db/index.ts
  src/helpers/index.ts
  src/index.ts
  src/interfaces/index.ts
  src/models/index.ts
  src/queries/index.ts
  src/routes/index.ts
  src/validation/index.ts
Labels: Approved

#11 Build client file structure
  client/.eslintrc.cjs
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/logo.svg
  client/src/App.tsx
  client/src/assets/logo.svg
  client/src/components/.gitkeep
  client/src/config.ts
  client/src/context/.gitkeep
  client/src/helpers/.gitkeep
  client/src/index.tsx
  client/src/interfaces/.gitkeep
  client/src/layouts/.gitkeep
  client/src/pages/.gitkeep
  client/src/routes/.gitkeep
  client/src/services/.gitkeep
  client/src/validations/.gitkeep
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: Awaiting Review

#16 The models were separated, each model with its own file.
  example.env
  package-lock.json
  package.json
  src/app.ts
  src/database/build.ts
  src/database/config.ts
  src/database/fakeData.ts
  src/database/index.ts
  src/database/init.sql
  src/db/index.ts
  src/index.ts
  src/interfaces/fakeDataTypes.ts
  src/interfaces/models.ts
  src/models/Category.ts
  src/models/Comment.ts
  src/models/Follower.ts
  src/models/Like.ts
  src/models/Pet.ts
  src/models/PetType.ts
  src/models/Post.ts
  src/models/PostImage.ts
  src/models/Product.ts
  src/models/User.ts
  src/models/index.ts
Labels: Awaiting Review

#25 Auth middleware
  src/app.ts
  src/controllers/user/getUser.ts
  src/controllers/user/index.ts
  src/helpers/CustomError.ts
  src/helpers/authToken.ts
  src/helpers/serverErrors.ts
  src/interfaces/iAuth.ts
  src/middlewares/auth.ts
  src/middlewares/checkType.ts
  src/queries/user/getUserQuery.ts
  src/queries/user/index.ts
Labels: Awaiting Review

#26 17 handle login
  __test__/auth.test.ts
  __test__/index.test.ts
  src/controllers/auth/index.ts
  src/controllers/auth/login.ts
  src/controllers/auth/signup.ts
  src/queries/auth/login.ts
  src/queries/auth/signup.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/validation/auth/login.ts
Labels: Approved, Done

#31 handle logout and clear token
  src/controllers/auth/index.ts
  src/controllers/auth/logout.ts
  src/routes/auth.ts
Labels: Approved

#32 Set github action configs
  .github/workflows/node.js.yml
Labels: Awaiting Review

#22 21 categories api
  __test__/category.test.ts
  package-lock.json
  package.json
  src/controllers/category/add.ts
  src/controllers/category/delete.ts
  src/controllers/category/edit.ts
  src/controllers/category/index.ts
  src/controllers/category/showAll.ts
  src/controllers/category/showById.ts
  src/interfaces/models.ts
  src/models/Category.ts
  src/queries/category/add.ts
  src/queries/category/delete.ts
  src/queries/category/edit.ts
  src/queries/category/showAll.ts
  src/queries/category/showById.ts
  src/routes/category.ts
  src/routes/index.ts
  src/validation/category/index.ts
  src/validation/category/validateCategoryId.ts
  src/validation/category/validateTitle.ts
  src/validation/index.ts
Labels: Approved

#36 35 change colums
  src/database/fakeData.ts
  src/interfaces/fakeDataTypes.ts
  src/interfaces/models.ts
  src/models/Comment.ts
  src/models/Follower.ts
  src/models/Like.ts
  src/models/Pet.ts
  src/models/PetType.ts
  src/models/Post.ts
  src/models/PostImage.ts
  src/models/Product.ts
  src/models/index.ts
Labels: Approved

#37 back end comment routre
  .github/workflows/node.js.yml
  __test__/category.test.ts
  __test__/comment.test.ts
  src/controllers/auth/login.ts
  src/controllers/auth/signup.ts
  src/controllers/category/createCategory.ts
  src/controllers/category/deleteCategory.ts
  src/controllers/category/index.ts
  src/controllers/category/showAllCategories.ts
  src/controllers/category/showCategoryById.ts
  src/controllers/category/updateCategory.ts
  src/controllers/comment/addComment.ts
  src/controllers/comment/deleteComment.ts
  src/controllers/comment/getComments.ts
  src/controllers/comment/getSpecificComment.ts
  src/controllers/comment/index.ts
  src/controllers/comment/updateComment.ts
  src/controllers/index.ts
  src/middlewares/auth.ts
  src/middlewares/checkType.ts
  src/queries/auth/index.ts
  src/queries/auth/signup.ts
  src/queries/category/addCategoryQuery.ts
  src/queries/category/deleteCategoryQuery.ts
  src/queries/category/editCategoryQuery.ts
  src/queries/category/getAllCategoriesQuery.ts
  src/queries/category/getSpecificCategoryQuery.ts
  src/queries/category/index.ts
  src/queries/comment/addCommentQuery.ts
  src/queries/comment/deleteCommentQuery.ts
  src/queries/comment/getCommentsQuery.ts
  src/queries/comment/getSpecificCommentQuery.ts
  src/queries/comment/index.ts
  src/queries/comment/updateCommentQuery.ts
  src/queries/index.ts
  src/routes/auth.ts
  src/routes/category.ts
  src/routes/comment.ts
  src/routes/index.ts
  src/validation/comment/addComment.ts
  src/validation/comment/deleteComment.ts
  src/validation/comment/index.ts
  src/validation/index.ts
Labels: Approved

#39 petType route with validation and tets
  __test__/pettype.test.ts
  src/controllers/index.ts
  src/controllers/petType/createPetType.ts
  src/controllers/petType/deletePetType.ts
  src/controllers/petType/editPetType.ts
  src/controllers/petType/getAllPetTypes.ts
  src/controllers/petType/getPetTypeById.ts
  src/controllers/petType/index.ts
  src/helpers/serverErrors.ts
  src/queries/index.ts
  src/queries/petType/createPetTypeQuery.ts
  src/queries/petType/deletePetTypeQuery.ts
  src/queries/petType/editPetTypeQuery.ts
  src/queries/petType/getAllPetTypesQuery.ts
  src/queries/petType/getPetTypeByIdQuery.ts
  src/queries/petType/index.ts
  src/routes/index.ts
  src/routes/type.ts
  src/validation/index.ts
  src/validation/pettype/index.ts
  src/validation/pettype/validateTitle.ts
  src/validation/pettype/validateTypeId.ts
Labels: Approved

#47 handle limit comments
  src/controllers/comment/getComments.ts
  src/queries/comment/getCommentsQuery.ts
Labels: Approved

#45 back end users router
  __test__/user.test.ts
  src/controllers/index.ts
  src/controllers/user/getAllUsers.ts
  src/controllers/user/getUser.ts
  src/controllers/user/index.ts
  src/models/User.ts
  src/queries/index.ts
  src/queries/user/getAllUsersQuery.ts
  src/queries/user/getUserQuery.ts
  src/queries/user/index.ts
  src/routes/index.ts
  src/routes/user.ts
  src/validation/index.ts
  src/validation/user/index.ts
  src/validation/user/validateUserId.ts
Labels: Approved

#43 42 post likes
  __test__/like.test.ts
  src/controllers/index.ts
  src/controllers/likes/createLike.ts
  src/controllers/likes/getPostLikers.ts
  src/controllers/likes/index.ts
  src/controllers/likes/unLike.ts
  src/database/fakeData.ts
  src/interfaces/fakeDataTypes.ts
  src/interfaces/models.ts
  src/models/Post.ts
  src/queries/index.ts
  src/queries/likes/createLikeQuery.ts
  src/queries/likes/getPostLikersQuery.ts
  src/queries/likes/index.ts
  src/queries/likes/unLikeQuery.ts
  src/routes/index.ts
  src/routes/like.ts
  src/validation/likes/index.ts
  src/validation/likes/validateLikeNum.ts
Labels: Approved

#51 handle activity status for users
  __test__/user.test.ts
  src/controllers/comment/getComments.ts
  src/controllers/index.ts
  src/controllers/user/index.ts
  src/controllers/user/userStatus.ts
  src/models/User.ts
  src/queries/index.ts
  src/queries/user/index.ts
  src/queries/user/userStatusQuery.ts
  src/routes/user.ts
  src/validation/index.ts
  src/validation/user/index.ts
  src/validation/user/validateStatus.ts
Labels: Awaiting Review

#29 backend posts routes
  .github/workflows/node.js.yml
  __test__/post.test.ts
  src/controllers/comment/deleteComment.ts
  src/controllers/index.ts
  src/controllers/post/addPost.ts
  src/controllers/post/deletePost.ts
  src/controllers/post/getExplorePosts.ts
  src/controllers/post/getSinglePost.ts
  src/controllers/post/index.ts
  src/controllers/post/updatePost.ts
  src/controllers/user/getUserPosts.ts
  src/controllers/user/index.ts
  src/database/fakeData.ts
  src/interfaces/fakeDataTypes.ts
  src/interfaces/iPosts.ts
  src/interfaces/models.ts
  src/middlewares/checkType.ts
  src/models/Pet.ts
  src/models/Post.ts
  src/models/index.ts
  src/queries/comment/addCommentQuery.ts
  src/queries/comment/deleteCommentQuery.ts
  src/queries/image/addImageQuery.ts
  src/queries/image/deleteImageQuery.ts
  src/queries/image/index.ts
  src/queries/index.ts
  src/queries/pet/addPetQuery.ts
  src/queries/pet/index.ts
  src/queries/pet/updatePetQuery.ts
  src/queries/post/addPostQuery.ts
  src/queries/post/deletePostQuery.ts
  src/queries/post/getExplorePostsQuery.ts
  src/queries/post/getPostQuery.ts
  src/queries/post/index.ts
  src/queries/post/updatePostQuery.ts
  src/queries/product/addProductQuery.ts
  src/queries/product/index.ts
  src/queries/product/updateProductQuery.ts
  src/queries/user/getUserPostsQuery.ts
  src/queries/user/index.ts
  src/routes/index.ts
  src/routes/post.ts
  src/routes/user.ts
  src/validation/post/addImages.ts
  src/validation/post/addPet.ts
  src/validation/post/addPost.ts
  src/validation/post/addProduct.ts
  src/validation/post/index.ts
Labels: Awaiting Review

#50 44 02 update profile
  __test__/updateProfile.test.ts
  src/controllers/index.ts
  src/controllers/user/index.ts
  src/controllers/user/updateUser.ts
  src/queries/user/editUserQuery.ts
  src/queries/user/getUserQuery.ts
  src/queries/user/index.ts
  src/routes/user.ts
  src/validation/auth/signup.ts
  src/validation/user/editUser.ts
  src/validation/user/index.ts
Labels: Approved

#41 Follow routes
  __test__/follow.test.ts
  __test__/user.test.ts
  src/controllers/auth/signup.ts
  src/controllers/follow/createFollow.ts
  src/controllers/follow/index.ts
  src/controllers/follow/showUserFollowers.ts
  src/controllers/follow/showUserFollowing.ts
  src/controllers/follow/unFollowUser.ts
  src/controllers/index.ts
  src/database/fakeData.ts
  src/interfaces/fakeDataTypes.ts
  src/interfaces/models.ts
  src/middlewares/checkType.ts
  src/models/User.ts
  src/models/index.ts
  src/queries/auth/signup.ts
  src/queries/follow/createFollowQuery.ts
  src/queries/follow/index.ts
  src/queries/follow/showUserFollowersQuery.ts
  src/queries/follow/showUserFollowingQuery.ts
  src/queries/follow/unfollowUserQuery.ts
  src/routes/follow.ts
  src/routes/index.ts
  src/validation/follow/index.ts
  src/validation/follow/validateFollowNum.ts
Labels: Awaiting Review

#56 Search About User By FullName With tests file
  __test__/searchUserName.test.ts
  src/controllers/index.ts
  src/controllers/user/index.ts
  src/controllers/user/searchAboutUser.ts
  src/queries/index.ts
  src/queries/user/index.ts
  src/queries/user/searchAboutUserQuery.ts
  src/routes/user.ts
  src/validation/index.ts
  src/validation/user/index.ts
  src/validation/user/validateStatus.ts
Labels: Awaiting Review

#55 Get feed post backend
  __test__/post.test.ts
  src/controllers/index.ts
  src/controllers/post/getFeedPosts.ts
  src/controllers/post/index.ts
  src/queries/index.ts
  src/queries/post/getFeedPostsQuery.ts
  src/queries/post/index.ts
  src/routes/post.ts
Labels: Approved

#65 checkAuth and change on post
  src/controllers/auth/checkAuth.ts
  src/controllers/auth/index.ts
  src/controllers/index.ts
  src/queries/category/getAllCategoriesQuery.ts
  src/queries/post/getExplorePostsQuery.ts
  src/queries/post/getFeedPostsQuery.ts
  src/queries/post/getPostQuery.ts
  src/queries/user/getUserPostsQuery.ts
  src/routes/auth.ts
Labels: Approved

#59 post card component
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/.gitkeep
  client/src/components/commons/Box.tsx
  client/src/components/commons/Carousel.tsx
  client/src/components/commons/Image.tsx
  client/src/components/commons/Paragraph.tsx
  client/src/components/post/CommentForm.tsx
  client/src/components/post/Label.tsx
  client/src/components/post/PostButtons.tsx
  client/src/components/post/PostCard.tsx
  client/src/components/post/PostComment.tsx
  client/src/components/post/PostDetails.tsx
  client/src/components/post/ShareComponent.tsx
  client/src/components/post/SingleComment.tsx
  client/src/helpers/fakeData.json
  client/src/helpers/timeFormatter.ts
  client/src/index.css
  client/src/index.tsx
  client/src/interfaces/IPost.ts
  client/src/interfaces/index.ts
  client/src/styles/post-card.css
  package.json
Labels: Approved

#69 Hot Fix get user query
  __test__/user.test.ts
  src/queries/user/getUserQuery.ts
Labels: Awaiting Review
