Repository GSG-G13/Petopia, pull requests merged in 2023-07, with the labels that each got.

#70 Pages error loading
  client/package-lock.json
  client/package.json
  client/public/notFound.gif
  client/public/preloader.gif
  client/src/App.tsx
  client/src/components/commons/LoadingComponent.tsx
  client/src/components/commons/PageNotFound.tsx
  client/src/components/context/AuthContext.tsx
  client/src/components/post/ShareComponent.tsx
  client/src/context/.gitkeep
  client/src/index.css
  client/src/index.tsx
  client/src/routes/router.tsx
  client/src/styles/error.css
  client/src/styles/loading.css
  package-lock.json
Labels: Approved

#72 fix likers bug
  __test__/like.test.ts
  src/controllers/likes/getPostLikers.ts
Labels: bug, Awaiting Review

#74 fix bugs
  src/models/Comment.ts
  src/models/Post.ts
  src/models/Product.ts
  src/queries/likes/unLikeQuery.ts
Labels: Awaiting Review

#75 profile posts
  client/src/components/PostContainer.tsx
  client/src/components/post/PostCard.tsx
  client/src/components/post/PostLikers.tsx
  client/src/components/post/SingleComment.tsx
  client/src/routes/router.tsx
Labels: Awaiting Review

#60 signup page
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/assets/Rectangle.png
  client/src/assets/pet.png
  client/src/index.tsx
  client/src/pages/.gitkeep
  client/src/pages/SignUp.tsx
  client/src/routes/router.tsx
  client/src/styles/Register.css
  src/app.ts
  src/validation/auth/signup.ts
Labels: Awaiting Review

#68 login page
  client/src/assets/Rectangle.png
  client/src/pages/Login.tsx
  client/src/routes/router.tsx
  src/validation/auth/signup.ts
Labels: Awaiting Review

#62 Add New Posts Component
  __test__/post.test.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/PostContainer.tsx
  client/src/components/addPost/AddAdoptionModal.tsx
  client/src/components/addPost/AddNewPost.tsx
  client/src/components/addPost/AddProductModal.tsx
  client/src/components/addPost/NormalPostModal.tsx
  client/src/components/addPost/addPost.css
  client/src/components/context/AuthContext.tsx
  client/src/components/post/Label.tsx
  client/src/helpers/uploadToCloudinary.ts
  client/src/interfaces/IPetType.ts
  client/src/interfaces/index.ts
  client/src/routes/router.tsx
  src/queries/post/getFeedPostsQuery.ts
Labels: Awaiting Review

#64 Left SideBar Component
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/HomePage.tsx
  client/src/components/PostContainer.tsx
  client/src/components/addPost/AddNewPostSideBar.tsx
  client/src/components/addPost/addPost.css
  client/src/components/context/AuthContext.tsx
  client/src/components/context/FollowingCountContext.tsx
  client/src/components/post/Label.tsx
  client/src/components/post/PostLikers.tsx
  client/src/components/sideBars/Follow.tsx
  client/src/components/sideBars/LeftSide.tsx
  client/src/components/sideBars/LeftSideBox.tsx
  client/src/components/sideBars/RightSide.tsx
  client/src/components/sideBars/TopRightSide.tsx
  client/src/components/sideBars/Trending.tsx
  client/src/components/sideBars/UsersModal.tsx
  client/src/components/useWindowSize.tsx
  client/src/components/userProfile/UserProfile.tsx
  client/src/index.css
  client/src/interfaces/IFollow.ts
  client/src/interfaces/IFollowingContext.ts
  client/src/interfaces/IUser.ts
  client/src/interfaces/index.ts
  client/src/routes/router.tsx
  client/src/styles/post-card.css
  client/src/styles/posts.css
  client/src/styles/profile.css
  package-lock.json
  src/app.ts
  src/queries/follow/unfollowUserQuery.ts
  src/queries/user/getAllUsersQuery.ts
Labels: Awaiting Review

#82 get stats
  __test__/stats.test.ts
  src/controllers/index.ts
  src/controllers/stats/getStats.ts
  src/controllers/stats/index.ts
  src/queries/index.ts
  src/queries/stats/getStatsQuery.ts
  src/queries/stats/index.ts
  src/routes/index.ts
  src/routes/stats.ts
Labels: Awaiting Review

#77 71 dashboard
  client/package-lock.json
  client/package.json
  client/src/components/AdminProtectedRoute.tsx
  client/src/components/ProtectedRoute.tsx
  client/src/components/dashboard/Categories.tsx
  client/src/components/dashboard/DashBoard.tsx
  client/src/components/dashboard/Posts.tsx
  client/src/components/dashboard/SideBar.tsx
  client/src/components/dashboard/Stats.tsx
  client/src/components/dashboard/Users.tsx
  client/src/components/sideBars/LeftSide.tsx
  client/src/routes/router.tsx
  client/src/styles/dashboard.css
  package-lock.json
Labels: Awaiting Review

#81 Edit post functionality
  __test__/post.test.ts
  client/package-lock.json
  client/package.json
  client/src/components/HomePage.tsx
  client/src/components/PostContainer.tsx
  client/src/components/addPost/AddAdoptionModal.tsx
  client/src/components/addPost/AddNewPost.tsx
  client/src/components/addPost/AddProductModal.tsx
  client/src/components/addPost/NormalPostModal.tsx
  client/src/components/post/LikePost.tsx
  client/src/components/post/PostAction.tsx
  client/src/components/post/PostButtons.tsx
  client/src/components/post/PostCard.tsx
  client/src/components/sideBars/Follow.tsx
  client/src/components/sideBars/LeftSide.tsx
  client/src/components/sideBars/LeftSideBox.tsx
  client/src/components/sideBars/RightSide.tsx
  client/src/components/sideBars/TopRightSide.tsx
  client/src/components/sideBars/Trending.tsx
  client/src/components/userProfile/UserProfile.tsx
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/src/styles/Register.css
  client/src/styles/error.css
  client/src/styles/post-card.css
  src/database/fakeData.ts
Labels: Awaiting Review
